# Header
menu:
  首页: /
  友链: /links
  关于: /about

# 主页banner图
banner: https://storage.deepin.org/thread/202307091951125992_linux%E8%83%8C%E6%99%AF%E5%9B%BE.png



# 站点通知信息
notice: 随便写点，牢骚，视频文案，贼辣鸡的文章，还有……随便乱写的小说

# 作者信息
author:
  name: XXTXTOP
  avatar: https://media.discordapp.net/attachments/1064543829807595580/1105328985514201179/IMG_4139.png
  description: 
  - 大家好，我是Linux爱好者XXTXTOP
  - 目前在使用deepin/uos等Linux发行版，在学习C/C++

toc:
  max_depth: 3 # 生成 TOC 的最大深度
  min_depth: 2 # 生成 TOC 的最小深度

comments:
  enable: false
  use: 'valine' # valine || disqus
  # valine 评论
  # docs: https://valine.js.org
  # You can get your appid and appkey from https://leancloud.cn
  # 这里appId和appKey一定一定要改成自己的，没有的话去https://leancloud.cn这个网站注册创建一个
  valine:
    appId: 
    appKey: 
    placeholder: 随便说点什么叭～ # 评论框占位提示符
    avatar: mp # Gravatar 头像展示方式
    pageSize: 10 # 评论列表分页，每页条数
    lang: zh-cn # 多语言支持
    visitor: true # 文章访问量统计
    recordIP: true # 是否记录评论者IP
    enableQQ: true # 是否启用昵称框自动获取QQ昵称和QQ头像，开启后是在昵称框输入QQ号码进行获取
    meta: "['nick', 'mail', 'link']" # 评论者相关属性，可选值：['nick']，['nick','mail']，['nick', 'mail', 'link']
    requiredFields: "['nick']" # 设置必填项，默认匿名
    bilibiliEmoji: true # 是否启用Bilibili表情
  # disqus 评论
  # docs: https://disqus.com/
  disqus:
    website: 
    error: 如果你看不到评论，那么就真的看不到评论 w(゜Д゜)w

# dplayer 视频播放
# docs: http://dplayer.js.org/#/zh-Hans/
dplayer:
  enable: true
  theme: "#b7daff"
  autoplay: false
  loop: false
  mutex: true

# aplayer 音频播放
# docs: https://aplayer.js.org/#/zh-Hans/
aplayer:
  enable: true
  theme: "#b7daff"
  autoplay: false
  loop: false
  mutex: true
  lrcType: 3

# mathjax LaTeX公式支持
#docs: http://docs.mathjax.org/en/latest/
mathjax:
    enable: true

# 国内备案信息
beian: 

# 谷歌分析
google_analytics: 
# gauges分析
gauges_analytics: 
# 百度分析
baidu_analytics: 
# 腾讯分析
tencent_analytics: 
# 站点ico
favicon: /favicon.ico


# Social Icon
social_icon:
  enable: true
  icons:
    ins     : https://github.com/XXTX-TOP
    zhihu   : https://github.com/XXTX-TOP
    weibo   : https://github.com/XXTX-TOP
    github  : https://github.com/XXTX-TOP
    twitter : https://github.com/XXTX-TOP
language: zh-CN